### ISSUE TITLE
PyVRP version pin

### ISSUE THREAD

**Issue by N-Wouda** [leonlan/dynamic-dispatch-waves#82]
We currently depend on some changes on top of PyVRP to support dispatch windows. These changes live on `main` in @leonlan's fork [here](https://github.com/leonlan/PyVRP). That's somewhat fragile for two reasons:

1. `main` is a moving target, so a few months down the line this version of the codebase is no longer the one we used for the DDWP paper. We do pin the revision, but this implicitly assumes the fork will have a main that has a different history from upstream PyVRP forever. In any case, we _must_ ensure the fork remains compatible with this repository, and that seems like an annoying compatibility guarantee.
2. This repo is not standalone 'enough'.

I propose we merge `main` from Leon's PyVRP fork into a `pyvrp` branch in this repository, and explicitly depend on that branch in our `pyproject.toml`. I think something like `branch = "pyvrp"` should work there. That ensures this repo is completely standalone.

**Comment by N-Wouda** [comment]
@leonlan what do you think?

**Comment by N-Wouda** [comment]
Yeah branches are possible: https://python-poetry.org/docs/dependency-specification/#git-dependencies.

**Comment by leonlan** [comment]
To understand it better: `pyproject.toml` currently points to a specific revision, so it doesn't really matter whether the fork's main is moving or not, right? Your suggestion to have a `pyvrp` branch on this repository would still require to pin the `pyproject.toml` to some revision, assuming that this repository might be updated in the future.

But overall I agree that it's better to have `pyvrp` in this repository rather than my fork.

**Comment by N-Wouda** [comment]
> `pyproject.toml` currently points to a specific revision, so it doesn't really matter whether the fork's main is moving or not, right?

Unless at some point you might want to remove that repo, or remove and pull main again from upstream, or do anything else that breaks that dependency. It's somewhat hard to predict what might happen, and this dependency is not explicit in the fork either.

> Your suggestion to have a `pyvrp` branch on this repository would still require to pin the `pyproject.toml` to some revision, assuming that this repository might be updated in the future.

I'm assuming we're archiving this repository after publication - and then it's nicely self-contained. Or do you have plans to work on this beyond the paper?

**Comment by leonlan** [comment]
> I'm assuming we're archiving this repository after publication - and then it's nicely self-contained. Or do you have plans to work on this beyond the paper?

Maybe, but now thinking about it again, I think it's better to have this repo (publically) archived and then continue that other project with a cloned repository. So yes, let's do what you suggested :-)

**Comment by N-Wouda** [comment]
Sounds good!
